# SPDX-FileCopyrightText: Copyright 2025-2026, macmpi
# SPDX-License-Identifier: MIT

# brcmfmac module parameters for stability
# https://github.com/RPi-Distro/firmware-nonfree/blob/trixie/debian/rpi-brcmfmac.conf
# Disable some brcmfmac driver features (internal roaming, FWSUP, SAE, DUMP_OBSS) while keeping SAE_EXT for WPA3
options brcmfmac roamoff=1 feature_disable=0x282000
